# 
#  Copyright (C) 2024 The pgmoneta community
# 
#  Redistribution and use in source and binary forms, with or without modification,
#  are permitted provided that the following conditions are met:
# 
#  1. Redistributions of source code must retain the above copyright notice, this list
#  of conditions and the following disclaimer.
# 
#  2. Redistributions in binary form must reproduce the above copyright notice, this
#  list of conditions and the following disclaimer in the documentation and/or other
#  materials provided with the distribution.
# 
#  3. Neither the name of the copyright holder nor the names of its contributors may
#  be used to endorse or promote products derived from this software without specific
#  prior written permission.
# 
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
#  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
#  THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
#  OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
#  TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 

FROM rockylinux:9

ARG PGVERSION

ENV PGVERSION=${PGVERSION}
ENV PGPASSWORD="secretpassword"
ENV PATH=/pgsql/bin:$PATH
ENV LD_LIBRARY_PATH=/pgsql/lib

RUN yum clean all && \
    yum update -y && \
    yum install -y epel-release && \
    yum install -y --allowerasing \
    git gcc cmake make bison readline-devel zlib-devel openssl-devel \
    wget ccache libicu-devel flex libxml2-devel libxslt-devel perl libev libev-devel \
    openssl openssl-devel systemd systemd-devel zlib zlib-devel libzstd libzstd-devel \
    lz4 lz4-devel libssh libssh-devel libcurl libcurl-devel python3-pip libatomic \
    bzip2 bzip2-devel libarchive libarchive-devel check check-devel && \
    yum groupinstall -y 'Development Tools' && \
    yum clean all && \
    pip3 install docutils

RUN useradd -m postgres && echo "postgres:${PGPASSWORD}" | chpasswd
RUN useradd -m pgmoneta && echo "pgmoneta:${PGPASSWORD}" | chpasswd

COPY conf/ /conf

RUN chmod -R 777 /conf && \
    mkdir -p /pgsql && \
    chown -R postgres:postgres /pgsql

# Install PostgreSQL 
RUN git clone --branch "REL_${PGVERSION}_STABLE" --single-branch --depth 1 https://github.com/postgres/postgres.git && \
    cd postgres && \
    ./configure --prefix=/pgsql && \
    make && \
    make install

RUN su - postgres -c "/pgsql/bin/initdb -D /pgsql/data" && \
    su - postgres -c "sed -i 's/^#\s*password_encryption\s*=\s*\(md5\|scram-sha-256\)/password_encryption = scram-sha-256/' /pgsql/data/postgresql.conf" && \
    su - postgres -c "sed -i 's/#wal_level = replica/wal_level = replica/' /pgsql/data/postgresql.conf && \
    cp -f /conf/pg_hba.conf /pgsql/data" && \
    chown -R postgres:postgres /pgsql/data && \
    su - postgres -c "/pgsql/bin/pg_ctl -D /pgsql/data -l /pgsql/logfile start" && \
    su - postgres -c "/pgsql/bin/psql -U postgres -c \"CREATE ROLE repl WITH LOGIN REPLICATION PASSWORD '${PGPASSWORD}';\"" && \
    su - postgres -c "/pgsql/bin/psql -U postgres -c \"SELECT pg_create_physical_replication_slot('repl', true, false);\"" && \
    su - postgres -c "/pgsql/bin/psql -c \"CREATE USER myuser WITH PASSWORD '${PGPASSWORD}';\"" && \
    su - postgres -c "/pgsql/bin/psql -c \"CREATE DATABASE mydb WITH OWNER myuser ENCODING 'UTF8';\"" && \
    su - postgres -c "/pgsql/bin/pg_ctl -D /pgsql/data -l /pgsql/logfile stop"

# Install pgmoneta
RUN git clone --branch "main" --single-branch --depth 1 https://github.com/pgmoneta/pgmoneta && \
    cd pgmoneta && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install && \
    cp -rf /conf/pgmoneta.conf /pgmoneta && \
    mkdir -p /pgmoneta/backup && \
    chown -R pgmoneta:pgmoneta /pgmoneta && \
    su - pgmoneta -c "/pgmoneta/build/src/pgmoneta-admin master-key -P ${PGPASSWORD}" && \
    su - pgmoneta -c "/pgmoneta/build/src/pgmoneta-admin -f /pgmoneta/pgmoneta_users.conf -U repl -P ${PGPASSWORD} user add"

# Install pgmoneta_ext
RUN git clone --branch "main" --single-branch --depth 1 https://github.com/pgmoneta/pgmoneta_ext && \
    cd pgmoneta_ext && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    make install && \
    echo "/pgsql/lib" >> /etc/ld.so.conf && \
    ldconfig && \
    su - postgres -c "/pgsql/bin/pg_ctl -D /pgsql/data -l /pgsql/logfile start" && \
    su - postgres -c "/pgsql/bin/psql -U postgres -c \"DROP EXTENSION IF EXISTS pgmoneta_ext;\"" && \
    su - postgres -c "/pgsql/bin/psql -U postgres -c \"CREATE EXTENSION pgmoneta_ext;\"" && \
    su - postgres -c "/pgsql/bin/pg_ctl -D /pgsql/data -l /pgsql/logfile stop"

CMD ["sh", "-c", "\
    su - postgres -c '/pgsql/bin/pg_ctl -D /pgsql/data -l /pgsql/logfile start' && \
    su - pgmoneta -c '/pgmoneta/build/src/pgmoneta -c /pgmoneta/pgmoneta.conf -u /pgmoneta/pgmoneta_users.conf -d' && \
    su - pgmoneta -c '/pgmoneta/build/src/pgmoneta-cli -c /pgmoneta/pgmoneta.conf details' && \
    /pgmoneta/build/test/pgmoneta_test && \
    su - pgmoneta -c '/pgmoneta/build/src/pgmoneta-cli -c /pgmoneta/pgmoneta.conf stop' \
"]