{
 "title": "pgmoneta dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgmoneta_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgmoneta_total_space", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgmoneta_used_space", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgmoneta_free_space", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Compression Algorithm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgmoneta_compression", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Used Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pgmoneta_used_space", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Free Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pgmoneta_free_space", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Retention",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgmoneta_retention_days", "legendFormat": "{{__name__}}" },
    { "expr": "pgmoneta_retention_weeks", "legendFormat": "{{__name__}}" },
    { "expr": "pgmoneta_retention_months", "legendFormat": "{{__name__}}" },
    { "expr": "pgmoneta_retention_years", "legendFormat": "{{__name__}}" }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Server State",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    { "expr": "pgmoneta_server_valid", "legendFormat": "__auto" },
    { "expr": "pgmoneta_wal_streaming", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Server Retention",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    { "expr": "pgmoneta_retention_server", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Size",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pgmoneta_total_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pgmoneta_total_size", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Client Operation Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "pgmoneta_server_operation_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "pgmoneta_server_failed_operation_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "pgmoneta_server_last_operation_time"
    },
    {
     "expr": "pgmoneta_server_last_failed_operation_time"
    }
   ]
  },
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Backup Infomation",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    { "expr": "pgmoneta_backup", "legendFormat": "__auto" },
    { "expr": "pgmoneta_backup_elapsed_time", "legendFormat": "__auto" },
    { "expr": "pgmoneta_backup_size", "legendFormat": "__auto" },
    { "expr": "pgmoneta_restore_size", "legendFormat": "__auto" },
    { "expr": "pgmoneta_backup_retain", "legendFormat": "__auto" },
    { "expr": "pgmoneta_backup_version", "legendFormat": "__auto" },
    {
     "expr": "pgmoneta_restore_size_increment",
     "legendFormat": "__auto"
    },
    {
     "expr": "pgmoneta_backup_compression_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Special Backup",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    { "expr": "pgmoneta_backup_oldest", "legendFormat": "__auto" },
    { "expr": "pgmoneta_backup_newest", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Newest Restore Size",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pgmoneta_restore_newest_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backup Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pgmoneta_backup_valid", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backup Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pgmoneta_backup_valid", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Total Backup Size",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pgmoneta_backup_total_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Backup Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pgmoneta_backup_total_size", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "WAL Size",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pgmoneta_wal_total_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WAL Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pgmoneta_wal_total_size", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "WAL Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pgmoneta_wal_total_size[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WAL Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pgmoneta_wal_total_size[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}