{
 "title": "pgmoneta Overview",
 "tags": [
  "pgmoneta",
  "overview"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "pg_version_major",
    "label": "PostgreSQL Major Version",
    "query": {
     "query": "label_values(pgmoneta_backup_version, major)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgmoneta_state" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgmoneta_used_space", "legendFormat": "Used" },
    { "expr": "pgmoneta_free_space", "legendFormat": "Free" }
   ]
  },
  {
   "title": "Used Space History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pgmoneta_used_space", "legendFormat": "Used Space" }
   ]
  },
  {
   "title": "Server Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pgmoneta_server_online", "legendFormat": "Online" },
    { "expr": "pgmoneta_server_valid", "legendFormat": "Valid" }
   ]
  }
 ]
}